# Generated by Django 5.2.1 on 2025-06-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('INSTANT_BOOKING', 'instant_booking'), ('SCHEDULE_BOOKING', 'schedule_booking')], default='INSTANT_BOOKING', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'stripe'), ('COD', 'cod')], default='stripe', max_length=20),
        ),
    ]
