# Generated by Django 5.2.1 on 2025-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0002_booking_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='is_released_to_barber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
