# Generated by Django 5.2.1 on 2025-06-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersite', '0003_paymentmodel_is_released_to_barber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=15),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'stripe'), ('COD', 'cod'), ('WALLET', 'wallet')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
