# Generated by Django 5.2.1 on 2025-06-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_at', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='barber_portfolios/')),
                ('is_available', models.BooleanField(default=True)),
                ('travel_radius_km', models.FloatField(default=10.0, help_text='Maximum distance barber is willing to travel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
