# Generated by Django 5.2.1 on 2025-05-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
