# Generated by Django 5.2.1 on 2025-06-10 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 10, 5, 30, 54, 665145, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
