# Generated by Django 5.2.1 on 2025-06-04 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_reg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barberrequest',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='barber_profiles/'),
        ),
        migrations.AddField(
            model_name='barberrequest',
            name='registration_step',
            field=models.CharField(choices=[('personal_details', 'Personal Details'), ('documents_uploaded', 'Documents Uploaded'), ('under_review', 'Under Review'), ('completed', 'Completed')], default='personal_details', max_length=20),
        ),
        migrations.AlterField(
            model_name='barberrequest',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/certificates/'),
        ),
        migrations.AlterField(
            model_name='barberrequest',
            name='licence',
            field=models.FileField(blank=True, null=True, upload_to='documents/licences/'),
        ),
        migrations.AlterField(
            model_name='barberrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='barberrequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
