# Generated by Django 5.2.1 on 2025-06-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileservice.address'),
        ),
    ]
