# Generated by Django 5.2.1 on 2025-06-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileservice', '0002_remove_address_profile_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
